name = "cloudflare-pages"
compatibility_date = "2024-12-07"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "QA_POSTS"
# For development: Create your own KV namespace in Cloudflare dashboard
# and replace these IDs with your own
id = "8663cdbd0df44a408ebdbbc5100a6393"

[dev]
port = 8789