name = "cloudflare-pages"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "QA_POSTS"
id = "8663cdbd0df44a408ebdbbc5100a6393"